package com.portal.model.domain;
// Generated Sep 2, 2013 8:56:18 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Data generated by hbm2java
 * @author pavel.lepeev
 */
@Entity
@Table(name = "data")
public class Data implements java.io.Serializable {

	private int id;
	private Users users;
	private String login;
	private String password;

	public Data() {
	}

	public Data(int id) {
		this.id = id;
	}

	public Data(int id, Users users, String login, String password) {
		this.id = id;
		this.users = users;
		this.login = login;
		this.password = password;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "code")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "login")
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
