package com.portal.model.domain;
// Generated Sep 2, 2013 8:56:18 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users")
public class Users implements java.io.Serializable {

	private int code;
	private Roles roles;
	private String name;
	private Integer phone;
	private Date birth;
	private Set<Data> datas = new HashSet(0);

	public Users() {
	}

	public Users(int code) {
		this.code = code;
	}

	public Users(int code, Roles roles, String name, Integer phone, Date birth,
			Set<Data> datas) {
		this.code = code;
		this.roles = roles;
		this.name = name;
		this.phone = phone;
		this.birth = birth;
		this.datas = datas;
	}

	@Id
	@Column(name = "code", unique = true, nullable = false)
	public int getCode() {
		return this.code;
	}

	public void setCode(int code) {
		this.code = code;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codrol")
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "phone")
	public Integer getPhone() {
		return this.phone;
	}

	public void setPhone(Integer phone) {
		this.phone = phone;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birth", length = 13)
	public Date getBirth() {
		return this.birth;
	}

	public void setBirth(Date birth) {
		this.birth = birth;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Data> getDatas() {
		return this.datas;
	}

	public void setDatas(Set<Data> datas) {
		this.datas = datas;
	}

}
